# This file was generated by GoReleaser. DO NOT EDIT.
class Tusk < Formula
  desc "The modern task runner"
  homepage "https://github.com/zoonect-oss/tusk"
  version "0.6.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/zoonect-oss/tusk/releases/download/v0.6.2/tusk_0.6.2_darwin_amd64.tar.gz"
    sha256 "208d56d6c966c60d08457d758cec8e701ba9ea3c8468ce4d2127987d78175104"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/zoonect-oss/tusk/releases/download/v0.6.2/tusk_0.6.2_linux_amd64.tar.gz"
      sha256 "6fd7f401b69e33129180cca9525282ae38c1f649e479727f6c9f57281ffad301"
    end
  end

  def install
    bin.install "tusk"
    
    bash_completion.install "completion/tusk-completion.bash"
    zsh_completion.install "completion/_tusk"
  end

  test do
    system "#{bin}/tusk --version"
  end
end
